/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthForm: typeof import('./components/auth/AuthForm.vue')['default']
    DashboardAvatar: typeof import('./components/dashboard/DashboardAvatar.vue')['default']
    DashboardHeader: typeof import('./components/dashboard/DashboardHeader.vue')['default']
    DashboardNotification: typeof import('./components/dashboard/DashboardNotification.vue')['default']
    DashboardSearch: typeof import('./components/dashboard/DashboardSearch.vue')['default']
    DashboardSidebar: typeof import('./components/dashboard/DashboardSidebar.vue')['default']
    IconCustomCheckin: typeof import('~icons/custom/checkin')['default']
    IconCustomHotel: typeof import('~icons/custom/hotel')['default']
    IconCustomMoney: typeof import('~icons/custom/money')['default']
    IconCustomRate: typeof import('~icons/custom/rate')['default']
    IconCustomSiphoriaNotext: typeof import('~icons/custom/siphoria-notext')['default']
    IconCustomSiphoriaText: typeof import('~icons/custom/siphoria-text')['default']
    IconCustomVoucher: typeof import('~icons/custom/voucher')['default']
    'IconPh:bellBold': typeof import('~icons/ph/bell-bold')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarHotel: typeof import('./components/dashboard/SidebarHotel.vue')['default']
    SidebarItem: typeof import('./components/dashboard/SidebarItem.vue')['default']
    SignupForm: typeof import('./components/auth/SignupForm.vue')['default']
  }
}
